# FMKMF_F90 not set: using f90
# FMKMF_SFTAG not set: using f90
# FMKMF_SPATH not set: using . 
# FMKMF_LINKOPTS not set: using no link options 
# Using compile cmd ifort from cmd line
# Using openmp
# Using opt
# Using m64
# Main program is find_best_cls.f90 
# process_fsource called with arg find_best_cls.f90 
# find_best_cls.f90 Uses Module simple_stkspi
# find_best_cls.f90 Uses Module simple_imgspi
# find_best_cls.f90 Uses Module simple_math
# find_best_cls.f90 Uses Module simple_cmdline
# find_best_cls.f90 Uses Module simple_params
# find_best_cls.f90 Uses Module simple_dens_map
# find_best_cls.f90 Uses Module simple_pair_wtab
# find_best_cls.f90 Uses Module simple_stat
# find_best_cls.f90 Uses Module simple_heapsort
# Full list of modules in find_best_cls.f90: simple_stkspi simple_imgspi simple_math simple_cmdline simple_params simple_dens_map simple_pair_wtab simple_stat simple_heapsort 
# Uses simple_stkspi which is in ../simple_stkspi.f90
# process_fsource called with arg ../simple_stkspi.f90 
# ../simple_stkspi.f90 Uses Module simple_jiffys
# ../simple_stkspi.f90 Uses Module simple_params
# ../simple_stkspi.f90 Uses Module simple_imgspi
# Full list of modules in ../simple_stkspi.f90: simple_jiffys simple_params simple_imgspi 
# Uses simple_jiffys which is in ../simple_jiffys.f90
# process_fsource called with arg ../simple_jiffys.f90 
# Full list of modules in ../simple_jiffys.f90:  
# Uses simple_params which is in ../simple_params.f90
# process_fsource called with arg ../simple_params.f90 
# ../simple_params.f90 Uses Module simple_jiffys
# ../simple_params.f90 Uses Module simple_cmdline
# Full list of modules in ../simple_params.f90: simple_jiffys simple_cmdline 
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_cmdline which is in ../simple_cmdline.f90
# process_fsource called with arg ../simple_cmdline.f90 
# Full list of modules in ../simple_cmdline.f90:  
# Uses simple_imgspi which is in ../simple_imgspi.f90
# process_fsource called with arg ../simple_imgspi.f90 
# ../simple_imgspi.f90 Uses Module simple_math
# ../simple_imgspi.f90 Uses Module gnufor2
# ../simple_imgspi.f90 Uses Module simple_jiffys
# ../simple_imgspi.f90 Uses Module simple_stat
# ../simple_imgspi.f90 Uses Module simple_params
# ../simple_imgspi.f90 Uses Module simple_dens_map
# Full list of modules in ../simple_imgspi.f90: simple_math gnufor2 simple_jiffys simple_stat simple_params simple_dens_map 
# Uses simple_math which is in ../simple_math.f90
# process_fsource called with arg ../simple_math.f90 
# ../simple_math.f90 Uses Module simple_def_precision
# ../simple_math.f90 Uses Module simple_syscalls
# ../simple_math.f90 Uses Module simple_jiffys
# ../simple_math.f90 Uses Module simple_rnd
# Full list of modules in ../simple_math.f90: simple_def_precision simple_syscalls simple_jiffys simple_rnd 
# Uses simple_def_precision which is in ../simple_def_precision.f90
# process_fsource called with arg ../simple_def_precision.f90 
# Full list of modules in ../simple_def_precision.f90:  
# Uses simple_syscalls which is in ../simple_syscalls.f90
# process_fsource called with arg ../simple_syscalls.f90 
# Full list of modules in ../simple_syscalls.f90:  
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_rnd which is in ../simple_rnd.f90
# process_fsource called with arg ../simple_rnd.f90 
# Full list of modules in ../simple_rnd.f90:  
# Uses gnufor2 which is in ../gnufor2.f90
# process_fsource called with arg ../gnufor2.f90 
# Full list of modules in ../gnufor2.f90:  
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_stat which is in ../simple_stat.f90
# process_fsource called with arg ../simple_stat.f90 
# ../simple_stat.f90 Uses Module simple_def_precision
# ../simple_stat.f90 Uses Module simple_pair_wtab
# ../simple_stat.f90 Uses Module simple_sll_list
# ../simple_stat.f90 Uses Module simple_jiffys
# ../simple_stat.f90 Uses Module simple_math
# ../simple_stat.f90 Uses Module simple_rnd
# ../simple_stat.f90 Uses Module simple_params
# Full list of modules in ../simple_stat.f90: simple_def_precision simple_pair_wtab simple_sll_list simple_jiffys simple_math simple_rnd simple_params 
# Uses simple_def_precision which is in ../simple_def_precision.f90
# ../simple_def_precision.f90 already in list
# Uses simple_pair_wtab which is in ../simple_pair_wtab.f90
# process_fsource called with arg ../simple_pair_wtab.f90 
# ../simple_pair_wtab.f90 Uses Module simple_jiffys
# Full list of modules in ../simple_pair_wtab.f90: simple_jiffys 
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_sll_list which is in ../simple_sll_list.f90
# process_fsource called with arg ../simple_sll_list.f90 
# ../simple_sll_list.f90 Uses Module simple_list_object
# ../simple_sll_list.f90 Uses Module simple_def_precision
# Full list of modules in ../simple_sll_list.f90: simple_list_object simple_def_precision 
# Uses simple_list_object which is in ../simple_list_object.f90
# process_fsource called with arg ../simple_list_object.f90 
# ../simple_list_object.f90 Uses Module simple_i_scalar
# ../simple_list_object.f90 Uses Module simple_r_scalar
# ../simple_list_object.f90 Uses Module simple_d_scalar
# ../simple_list_object.f90 Uses Module simple_i_array
# ../simple_list_object.f90 Uses Module simple_r_array
# ../simple_list_object.f90 Uses Module simple_d_array
# Full list of modules in ../simple_list_object.f90: simple_i_scalar simple_r_scalar simple_d_scalar simple_i_array simple_r_array simple_d_array 
# Uses simple_i_scalar which is in ../simple_i_scalar.f90
# process_fsource called with arg ../simple_i_scalar.f90 
# Full list of modules in ../simple_i_scalar.f90:  
# Uses simple_r_scalar which is in ../simple_r_scalar.f90
# process_fsource called with arg ../simple_r_scalar.f90 
# Full list of modules in ../simple_r_scalar.f90:  
# Uses simple_d_scalar which is in ../simple_d_scalar.f90
# process_fsource called with arg ../simple_d_scalar.f90 
# ../simple_d_scalar.f90 Uses Module simple_def_precision
# Full list of modules in ../simple_d_scalar.f90: simple_def_precision 
# Uses simple_def_precision which is in ../simple_def_precision.f90
# ../simple_def_precision.f90 already in list
# Uses simple_i_array which is in ../simple_i_array.f90
# process_fsource called with arg ../simple_i_array.f90 
# ../simple_i_array.f90 Uses Module simple_jiffys
# Full list of modules in ../simple_i_array.f90: simple_jiffys 
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_r_array which is in ../simple_r_array.f90
# process_fsource called with arg ../simple_r_array.f90 
# ../simple_r_array.f90 Uses Module simple_jiffys
# Full list of modules in ../simple_r_array.f90: simple_jiffys 
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_d_array which is in ../simple_d_array.f90
# process_fsource called with arg ../simple_d_array.f90 
# ../simple_d_array.f90 Uses Module simple_def_precision
# ../simple_d_array.f90 Uses Module simple_jiffys
# Full list of modules in ../simple_d_array.f90: simple_def_precision simple_jiffys 
# Uses simple_def_precision which is in ../simple_def_precision.f90
# ../simple_def_precision.f90 already in list
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_def_precision which is in ../simple_def_precision.f90
# ../simple_def_precision.f90 already in list
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_math which is in ../simple_math.f90
# ../simple_math.f90 already in list
# Uses simple_rnd which is in ../simple_rnd.f90
# ../simple_rnd.f90 already in list
# Uses simple_params which is in ../simple_params.f90
# ../simple_params.f90 already in list
# Uses simple_params which is in ../simple_params.f90
# ../simple_params.f90 already in list
# Uses simple_dens_map which is in ../simple_dens_map.f90
# process_fsource called with arg ../simple_dens_map.f90 
# ../simple_dens_map.f90 Uses Module simple_math
# ../simple_dens_map.f90 Uses Module simple_stat
# Full list of modules in ../simple_dens_map.f90: simple_math simple_stat 
# Uses simple_math which is in ../simple_math.f90
# ../simple_math.f90 already in list
# Uses simple_stat which is in ../simple_stat.f90
# ../simple_stat.f90 already in list
# Uses simple_imgspi which is in ../simple_imgspi.f90
# ../simple_imgspi.f90 already in list
# Uses simple_math which is in ../simple_math.f90
# ../simple_math.f90 already in list
# Uses simple_cmdline which is in ../simple_cmdline.f90
# ../simple_cmdline.f90 already in list
# Uses simple_params which is in ../simple_params.f90
# ../simple_params.f90 already in list
# Uses simple_dens_map which is in ../simple_dens_map.f90
# ../simple_dens_map.f90 already in list
# Uses simple_pair_wtab which is in ../simple_pair_wtab.f90
# ../simple_pair_wtab.f90 already in list
# Uses simple_stat which is in ../simple_stat.f90
# ../simple_stat.f90 already in list
# Uses simple_heapsort which is in ../simple_heapsort.f90
# process_fsource called with arg ../simple_heapsort.f90 
# ../simple_heapsort.f90 Uses Module simple_sll_list
# ../simple_heapsort.f90 Uses Module simple_math
# ../simple_heapsort.f90 Uses Module simple_def_precision
# Full list of modules in ../simple_heapsort.f90: simple_sll_list simple_math simple_def_precision 
# Uses simple_sll_list which is in ../simple_sll_list.f90
# ../simple_sll_list.f90 already in list
# Uses simple_math which is in ../simple_math.f90
# ../simple_math.f90 already in list
# Uses simple_def_precision which is in ../simple_def_precision.f90
# ../simple_def_precision.f90 already in list

# ------------------Macro-Defs---------------------
F90=ifort 

# -------------------End-macro-Defs---------------------------

# Here is the link step 
find_best_cls:simple_jiffys.o simple_cmdline.o simple_params.o simple_def_precision.o simple_syscalls.o simple_rnd.o simple_math.o gnufor2.o simple_pair_wtab.o simple_i_scalar.o simple_r_scalar.o simple_d_scalar.o simple_i_array.o simple_r_array.o simple_d_array.o simple_list_object.o simple_sll_list.o simple_stat.o simple_dens_map.o simple_imgspi.o simple_stkspi.o simple_heapsort.o find_best_cls.o 
	 $(F90) -o find_best_cls simple_jiffys.o simple_cmdline.o simple_params.o simple_def_precision.o simple_syscalls.o simple_rnd.o simple_math.o gnufor2.o simple_pair_wtab.o simple_i_scalar.o simple_r_scalar.o simple_d_scalar.o simple_i_array.o simple_r_array.o simple_d_array.o simple_list_object.o simple_sll_list.o simple_stat.o simple_dens_map.o simple_imgspi.o simple_stkspi.o simple_heapsort.o find_best_cls.o   -implicitnone -static -L../fftw/fftw3-3.3/ -lfftw3f -lfftw3f_threads -i-static

# Here are the compile steps
 
simple_jiffys.o:../simple_jiffys.f90  
	 $(F90) -c ../simple_jiffys.f90 -implicitnone -static -L../fftw/fftw3-3.3/ -lfftw3f -lfftw3f_threads -i-static

simple_cmdline.o:../simple_cmdline.f90  
	 $(F90) -c ../simple_cmdline.f90 -implicitnone -static -L../fftw/fftw3-3.3/ -lfftw3f -lfftw3f_threads -i-static

simple_params.o:../simple_params.f90 simple_jiffys.o simple_cmdline.o 
	 $(F90) -c ../simple_params.f90 -implicitnone -static -L../fftw/fftw3-3.3/ -lfftw3f -lfftw3f_threads -i-static

simple_def_precision.o:../simple_def_precision.f90  
	 $(F90) -c ../simple_def_precision.f90 -implicitnone -static -L../fftw/fftw3-3.3/ -lfftw3f -lfftw3f_threads -i-static

simple_syscalls.o:../simple_syscalls.f90  
	 $(F90) -c ../simple_syscalls.f90 -implicitnone -static -L../fftw/fftw3-3.3/ -lfftw3f -lfftw3f_threads -i-static

simple_rnd.o:../simple_rnd.f90  
	 $(F90) -c ../simple_rnd.f90 -implicitnone -static -L../fftw/fftw3-3.3/ -lfftw3f -lfftw3f_threads -i-static

simple_math.o:../simple_math.f90 simple_def_precision.o simple_syscalls.o simple_jiffys.o simple_rnd.o 
	 $(F90) -c ../simple_math.f90 -implicitnone -static -L../fftw/fftw3-3.3/ -lfftw3f -lfftw3f_threads -i-static

gnufor2.o:../gnufor2.f90  
	 $(F90) -c ../gnufor2.f90 -implicitnone -static -L../fftw/fftw3-3.3/ -lfftw3f -lfftw3f_threads -i-static

simple_pair_wtab.o:../simple_pair_wtab.f90 simple_jiffys.o 
	 $(F90) -c ../simple_pair_wtab.f90 -implicitnone -static -L../fftw/fftw3-3.3/ -lfftw3f -lfftw3f_threads -i-static

simple_i_scalar.o:../simple_i_scalar.f90  
	 $(F90) -c ../simple_i_scalar.f90 -implicitnone -static -L../fftw/fftw3-3.3/ -lfftw3f -lfftw3f_threads -i-static

simple_r_scalar.o:../simple_r_scalar.f90  
	 $(F90) -c ../simple_r_scalar.f90 -implicitnone -static -L../fftw/fftw3-3.3/ -lfftw3f -lfftw3f_threads -i-static

simple_d_scalar.o:../simple_d_scalar.f90 simple_def_precision.o 
	 $(F90) -c ../simple_d_scalar.f90 -implicitnone -static -L../fftw/fftw3-3.3/ -lfftw3f -lfftw3f_threads -i-static

simple_i_array.o:../simple_i_array.f90 simple_jiffys.o 
	 $(F90) -c ../simple_i_array.f90 -implicitnone -static -L../fftw/fftw3-3.3/ -lfftw3f -lfftw3f_threads -i-static

simple_r_array.o:../simple_r_array.f90 simple_jiffys.o 
	 $(F90) -c ../simple_r_array.f90 -implicitnone -static -L../fftw/fftw3-3.3/ -lfftw3f -lfftw3f_threads -i-static

simple_d_array.o:../simple_d_array.f90 simple_def_precision.o simple_jiffys.o 
	 $(F90) -c ../simple_d_array.f90 -implicitnone -static -L../fftw/fftw3-3.3/ -lfftw3f -lfftw3f_threads -i-static

simple_list_object.o:../simple_list_object.f90 simple_i_scalar.o simple_r_scalar.o simple_d_scalar.o simple_i_array.o simple_r_array.o simple_d_array.o 
	 $(F90) -c ../simple_list_object.f90 -implicitnone -static -L../fftw/fftw3-3.3/ -lfftw3f -lfftw3f_threads -i-static

simple_sll_list.o:../simple_sll_list.f90 simple_list_object.o simple_def_precision.o 
	 $(F90) -c ../simple_sll_list.f90 -implicitnone -static -L../fftw/fftw3-3.3/ -lfftw3f -lfftw3f_threads -i-static

simple_stat.o:../simple_stat.f90 simple_def_precision.o simple_pair_wtab.o simple_sll_list.o simple_jiffys.o simple_math.o simple_rnd.o simple_params.o 
	 $(F90) -c ../simple_stat.f90 -implicitnone -static -L../fftw/fftw3-3.3/ -lfftw3f -lfftw3f_threads -i-static

simple_dens_map.o:../simple_dens_map.f90 simple_math.o simple_stat.o 
	 $(F90) -c ../simple_dens_map.f90 -implicitnone -static -L../fftw/fftw3-3.3/ -lfftw3f -lfftw3f_threads -i-static

simple_imgspi.o:../simple_imgspi.f90 simple_math.o gnufor2.o simple_jiffys.o simple_stat.o simple_params.o simple_dens_map.o 
	 $(F90) -c ../simple_imgspi.f90 -implicitnone -static -L../fftw/fftw3-3.3/ -lfftw3f -lfftw3f_threads -i-static

simple_stkspi.o:../simple_stkspi.f90 simple_jiffys.o simple_params.o simple_imgspi.o 
	 $(F90) -c ../simple_stkspi.f90 -implicitnone -static -L../fftw/fftw3-3.3/ -lfftw3f -lfftw3f_threads -i-static

simple_heapsort.o:../simple_heapsort.f90 simple_sll_list.o simple_math.o simple_def_precision.o 
	 $(F90) -c ../simple_heapsort.f90 -implicitnone -static -L../fftw/fftw3-3.3/ -lfftw3f -lfftw3f_threads -i-static

find_best_cls.o:find_best_cls.f90 simple_stkspi.o simple_imgspi.o simple_math.o simple_cmdline.o simple_params.o simple_dens_map.o simple_pair_wtab.o simple_stat.o simple_heapsort.o 
	 $(F90) -c find_best_cls.f90 -implicitnone -static -L../fftw/fftw3-3.3/ -lfftw3f -lfftw3f_threads -i-static
# This entry allows you to type " make clean " to get rid of
# all object and module files 
clean:
	rm -f -r f_{files,modd}* *~ *.g90 *.o *.mod *.M *.d V*.inc *.vo \
	V*.f *.dbg album F.err
  
