# FMKMF_F90 not set: using f90
# FMKMF_SFTAG not set: using f90
# FMKMF_SPATH not set: using . 
# FMKMF_LINKOPTS not set: using no link options 
# Using compile cmd ifort from cmd line
# Using openmp
# Using opt
# Using m64
# Main program is classify.f90 
# process_fsource called with arg classify.f90 
# classify.f90 Uses Module simple_pmatch
# classify.f90 Uses Module simple_fstk
# classify.f90 Uses Module simple_spidoc
# classify.f90 Uses Module simple_params
# classify.f90 Uses Module simple_sll_list
# classify.f90 Uses Module simple_jiffys
# classify.f90 Uses Module simple_build
# classify.f90 Uses Module simple_ppca
# classify.f90 Uses Module simple_pair_wtab
# classify.f90 Uses Module simple_math
# classify.f90 Uses Module simple_cmdline
# Full list of modules in classify.f90: simple_pmatch simple_fstk simple_spidoc simple_params simple_sll_list simple_jiffys simple_build simple_ppca simple_pair_wtab simple_math simple_cmdline 
# Uses simple_pmatch which is in ../simple_pmatch.f90
# process_fsource called with arg ../simple_pmatch.f90 
# ../simple_pmatch.f90 Uses Module simple_fplanes_corr
# ../simple_pmatch.f90 Uses Module simple_math
# ../simple_pmatch.f90 Uses Module simple_build
# ../simple_pmatch.f90 Uses Module simple_params
# ../simple_pmatch.f90 Uses Module simple_rnd
# ../simple_pmatch.f90 Uses Module simple_stkspi
# ../simple_pmatch.f90 Uses Module simple_imgspi
# ../simple_pmatch.f90 Uses Module simple_jiffys
# ../simple_pmatch.f90 Uses Module simple_ran_tabu
# ../simple_pmatch.f90 Uses Module simple_fplane
# Full list of modules in ../simple_pmatch.f90: simple_fplanes_corr simple_math simple_build simple_params simple_rnd simple_stkspi simple_imgspi simple_jiffys simple_ran_tabu simple_fplane 
# Uses simple_fplanes_corr which is in ../simple_fplanes_corr.f90
# process_fsource called with arg ../simple_fplanes_corr.f90 
# ../simple_fplanes_corr.f90 Uses Module simple_eulers
# ../simple_fplanes_corr.f90 Uses Module simple_build
# ../simple_fplanes_corr.f90 Uses Module simple_params
# ../simple_fplanes_corr.f90 Uses Module simple_math
# ../simple_fplanes_corr.f90 Uses Module simple_jiffys
# ../simple_fplanes_corr.f90 Uses Module simple_def_precision
# Full list of modules in ../simple_fplanes_corr.f90: simple_eulers simple_build simple_params simple_math simple_jiffys simple_def_precision 
# Uses simple_eulers which is in ../simple_eulers.f90
# process_fsource called with arg ../simple_eulers.f90 
# ../simple_eulers.f90 Uses Module simple_heapsort
# ../simple_eulers.f90 Uses Module simple_math
# ../simple_eulers.f90 Uses Module simple_def_precision
# ../simple_eulers.f90 Uses Module simple_spidoc
# ../simple_eulers.f90 Uses Module simple_jiffys
# Full list of modules in ../simple_eulers.f90: simple_heapsort simple_math simple_def_precision simple_spidoc simple_jiffys 
# Uses simple_heapsort which is in ../simple_heapsort.f90
# process_fsource called with arg ../simple_heapsort.f90 
# ../simple_heapsort.f90 Uses Module simple_sll_list
# ../simple_heapsort.f90 Uses Module simple_math
# ../simple_heapsort.f90 Uses Module simple_def_precision
# Full list of modules in ../simple_heapsort.f90: simple_sll_list simple_math simple_def_precision 
# Uses simple_sll_list which is in ../simple_sll_list.f90
# process_fsource called with arg ../simple_sll_list.f90 
# ../simple_sll_list.f90 Uses Module simple_list_object
# ../simple_sll_list.f90 Uses Module simple_def_precision
# Full list of modules in ../simple_sll_list.f90: simple_list_object simple_def_precision 
# Uses simple_list_object which is in ../simple_list_object.f90
# process_fsource called with arg ../simple_list_object.f90 
# ../simple_list_object.f90 Uses Module simple_i_scalar
# ../simple_list_object.f90 Uses Module simple_r_scalar
# ../simple_list_object.f90 Uses Module simple_d_scalar
# ../simple_list_object.f90 Uses Module simple_i_array
# ../simple_list_object.f90 Uses Module simple_r_array
# ../simple_list_object.f90 Uses Module simple_d_array
# Full list of modules in ../simple_list_object.f90: simple_i_scalar simple_r_scalar simple_d_scalar simple_i_array simple_r_array simple_d_array 
# Uses simple_i_scalar which is in ../simple_i_scalar.f90
# process_fsource called with arg ../simple_i_scalar.f90 
# Full list of modules in ../simple_i_scalar.f90:  
# Uses simple_r_scalar which is in ../simple_r_scalar.f90
# process_fsource called with arg ../simple_r_scalar.f90 
# Full list of modules in ../simple_r_scalar.f90:  
# Uses simple_d_scalar which is in ../simple_d_scalar.f90
# process_fsource called with arg ../simple_d_scalar.f90 
# ../simple_d_scalar.f90 Uses Module simple_def_precision
# Full list of modules in ../simple_d_scalar.f90: simple_def_precision 
# Uses simple_def_precision which is in ../simple_def_precision.f90
# process_fsource called with arg ../simple_def_precision.f90 
# Full list of modules in ../simple_def_precision.f90:  
# Uses simple_i_array which is in ../simple_i_array.f90
# process_fsource called with arg ../simple_i_array.f90 
# ../simple_i_array.f90 Uses Module simple_jiffys
# Full list of modules in ../simple_i_array.f90: simple_jiffys 
# Uses simple_jiffys which is in ../simple_jiffys.f90
# process_fsource called with arg ../simple_jiffys.f90 
# Full list of modules in ../simple_jiffys.f90:  
# Uses simple_r_array which is in ../simple_r_array.f90
# process_fsource called with arg ../simple_r_array.f90 
# ../simple_r_array.f90 Uses Module simple_jiffys
# Full list of modules in ../simple_r_array.f90: simple_jiffys 
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_d_array which is in ../simple_d_array.f90
# process_fsource called with arg ../simple_d_array.f90 
# ../simple_d_array.f90 Uses Module simple_def_precision
# ../simple_d_array.f90 Uses Module simple_jiffys
# Full list of modules in ../simple_d_array.f90: simple_def_precision simple_jiffys 
# Uses simple_def_precision which is in ../simple_def_precision.f90
# ../simple_def_precision.f90 already in list
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_def_precision which is in ../simple_def_precision.f90
# ../simple_def_precision.f90 already in list
# Uses simple_math which is in ../simple_math.f90
# process_fsource called with arg ../simple_math.f90 
# ../simple_math.f90 Uses Module simple_def_precision
# ../simple_math.f90 Uses Module simple_syscalls
# ../simple_math.f90 Uses Module simple_jiffys
# ../simple_math.f90 Uses Module simple_rnd
# Full list of modules in ../simple_math.f90: simple_def_precision simple_syscalls simple_jiffys simple_rnd 
# Uses simple_def_precision which is in ../simple_def_precision.f90
# ../simple_def_precision.f90 already in list
# Uses simple_syscalls which is in ../simple_syscalls.f90
# process_fsource called with arg ../simple_syscalls.f90 
# Full list of modules in ../simple_syscalls.f90:  
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_rnd which is in ../simple_rnd.f90
# process_fsource called with arg ../simple_rnd.f90 
# Full list of modules in ../simple_rnd.f90:  
# Uses simple_def_precision which is in ../simple_def_precision.f90
# ../simple_def_precision.f90 already in list
# Uses simple_math which is in ../simple_math.f90
# ../simple_math.f90 already in list
# Uses simple_def_precision which is in ../simple_def_precision.f90
# ../simple_def_precision.f90 already in list
# Uses simple_spidoc which is in ../simple_spidoc.f90
# process_fsource called with arg ../simple_spidoc.f90 
# ../simple_spidoc.f90 Uses Module simple_sll_list
# ../simple_spidoc.f90 Uses Module simple_jiffys
# Full list of modules in ../simple_spidoc.f90: simple_sll_list simple_jiffys 
# Uses simple_sll_list which is in ../simple_sll_list.f90
# ../simple_sll_list.f90 already in list
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_build which is in ../simple_build.f90
# process_fsource called with arg ../simple_build.f90 
# ../simple_build.f90 Uses Module simple_params
# ../simple_build.f90 Uses Module simple_eulers
# ../simple_build.f90 Uses Module simple_comlin
# ../simple_build.f90 Uses Module simple_heapsort
# ../simple_build.f90 Uses Module simple_aligndata
# ../simple_build.f90 Uses Module simple_volspi
# ../simple_build.f90 Uses Module simple_jiffys
# ../simple_build.f90 Uses Module simple_math
# ../simple_build.f90 Uses Module simple_rnd
# ../simple_build.f90 Uses Module simple_ffts
# ../simple_build.f90 Uses Module simple_fplane
# Full list of modules in ../simple_build.f90: simple_params simple_eulers simple_comlin simple_heapsort simple_aligndata simple_volspi simple_jiffys simple_math simple_rnd simple_ffts simple_fplane 
# Uses simple_params which is in ../simple_params.f90
# process_fsource called with arg ../simple_params.f90 
# ../simple_params.f90 Uses Module simple_jiffys
# ../simple_params.f90 Uses Module simple_cmdline
# ../simple_params.f90 Uses Module simple_math
# Full list of modules in ../simple_params.f90: simple_jiffys simple_cmdline simple_math 
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_cmdline which is in ../simple_cmdline.f90
# process_fsource called with arg ../simple_cmdline.f90 
# Full list of modules in ../simple_cmdline.f90:  
# Uses simple_math which is in ../simple_math.f90
# ../simple_math.f90 already in list
# Uses simple_eulers which is in ../simple_eulers.f90
# ../simple_eulers.f90 already in list
# Uses simple_comlin which is in ../simple_comlin.f90
# process_fsource called with arg ../simple_comlin.f90 
# ../simple_comlin.f90 Uses Module simple_eulers
# ../simple_comlin.f90 Uses Module simple_math
# ../simple_comlin.f90 Uses Module simple_jiffys
# ../simple_comlin.f90 Uses Module simple_params
# Full list of modules in ../simple_comlin.f90: simple_eulers simple_math simple_jiffys simple_params 
# Uses simple_eulers which is in ../simple_eulers.f90
# ../simple_eulers.f90 already in list
# Uses simple_math which is in ../simple_math.f90
# ../simple_math.f90 already in list
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_params which is in ../simple_params.f90
# ../simple_params.f90 already in list
# Uses simple_heapsort which is in ../simple_heapsort.f90
# ../simple_heapsort.f90 already in list
# Uses simple_aligndata which is in ../simple_aligndata.f90
# process_fsource called with arg ../simple_aligndata.f90 
# ../simple_aligndata.f90 Uses Module simple_heapsort
# ../simple_aligndata.f90 Uses Module simple_jiffys
# Full list of modules in ../simple_aligndata.f90: simple_heapsort simple_jiffys 
# Uses simple_heapsort which is in ../simple_heapsort.f90
# ../simple_heapsort.f90 already in list
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_volspi which is in ../simple_volspi.f90
# process_fsource called with arg ../simple_volspi.f90 
# ../simple_volspi.f90 Uses Module simple_math
# ../simple_volspi.f90 Uses Module simple_jiffys
# ../simple_volspi.f90 Uses Module simple_params
# ../simple_volspi.f90 Uses Module simple_stat
# Full list of modules in ../simple_volspi.f90: simple_math simple_jiffys simple_params simple_stat 
# Uses simple_math which is in ../simple_math.f90
# ../simple_math.f90 already in list
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_params which is in ../simple_params.f90
# ../simple_params.f90 already in list
# Uses simple_stat which is in ../simple_stat.f90
# process_fsource called with arg ../simple_stat.f90 
# ../simple_stat.f90 Uses Module simple_def_precision
# ../simple_stat.f90 Uses Module simple_pair_wtab
# ../simple_stat.f90 Uses Module simple_sll_list
# ../simple_stat.f90 Uses Module simple_jiffys
# ../simple_stat.f90 Uses Module simple_math
# ../simple_stat.f90 Uses Module simple_rnd
# ../simple_stat.f90 Uses Module simple_params
# Full list of modules in ../simple_stat.f90: simple_def_precision simple_pair_wtab simple_sll_list simple_jiffys simple_math simple_rnd simple_params 
# Uses simple_def_precision which is in ../simple_def_precision.f90
# ../simple_def_precision.f90 already in list
# Uses simple_pair_wtab which is in ../simple_pair_wtab.f90
# process_fsource called with arg ../simple_pair_wtab.f90 
# ../simple_pair_wtab.f90 Uses Module simple_jiffys
# Full list of modules in ../simple_pair_wtab.f90: simple_jiffys 
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_sll_list which is in ../simple_sll_list.f90
# ../simple_sll_list.f90 already in list
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_math which is in ../simple_math.f90
# ../simple_math.f90 already in list
# Uses simple_rnd which is in ../simple_rnd.f90
# ../simple_rnd.f90 already in list
# Uses simple_params which is in ../simple_params.f90
# ../simple_params.f90 already in list
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_math which is in ../simple_math.f90
# ../simple_math.f90 already in list
# Uses simple_rnd which is in ../simple_rnd.f90
# ../simple_rnd.f90 already in list
# Uses simple_ffts which is in ../simple_ffts.f90
# process_fsource called with arg ../simple_ffts.f90 
# ../simple_ffts.f90 Uses Module simple_fftw3
# ../simple_ffts.f90 Uses Module simple_jiffys
# Full list of modules in ../simple_ffts.f90: simple_fftw3 simple_jiffys 
# Uses simple_fftw3 which is in ../simple_fftw3.f90
# process_fsource called with arg ../simple_fftw3.f90 
# Full list of modules in ../simple_fftw3.f90:  
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_fplane which is in ../simple_fplane.f90
# process_fsource called with arg ../simple_fplane.f90 
# ../simple_fplane.f90 Uses Module simple_math
# ../simple_fplane.f90 Uses Module simple_jiffys
# ../simple_fplane.f90 Uses Module simple_params
# ../simple_fplane.f90 Uses Module simple_stat
# ../simple_fplane.f90 Uses Module simple_imgspi
# ../simple_fplane.f90 Uses Module simple_ffts
# Full list of modules in ../simple_fplane.f90: simple_math simple_jiffys simple_params simple_stat simple_imgspi simple_ffts 
# Uses simple_math which is in ../simple_math.f90
# ../simple_math.f90 already in list
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_params which is in ../simple_params.f90
# ../simple_params.f90 already in list
# Uses simple_stat which is in ../simple_stat.f90
# ../simple_stat.f90 already in list
# Uses simple_imgspi which is in ../simple_imgspi.f90
# process_fsource called with arg ../simple_imgspi.f90 
# ../simple_imgspi.f90 Uses Module simple_math
# ../simple_imgspi.f90 Uses Module gnufor2
# ../simple_imgspi.f90 Uses Module simple_jiffys
# ../simple_imgspi.f90 Uses Module simple_stat
# ../simple_imgspi.f90 Uses Module simple_params
# ../simple_imgspi.f90 Uses Module simple_dens_map
# Full list of modules in ../simple_imgspi.f90: simple_math gnufor2 simple_jiffys simple_stat simple_params simple_dens_map 
# Uses simple_math which is in ../simple_math.f90
# ../simple_math.f90 already in list
# Uses gnufor2 which is in ../gnufor2.f90
# process_fsource called with arg ../gnufor2.f90 
# Full list of modules in ../gnufor2.f90:  
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_stat which is in ../simple_stat.f90
# ../simple_stat.f90 already in list
# Uses simple_params which is in ../simple_params.f90
# ../simple_params.f90 already in list
# Uses simple_dens_map which is in ../simple_dens_map.f90
# process_fsource called with arg ../simple_dens_map.f90 
# ../simple_dens_map.f90 Uses Module simple_math
# ../simple_dens_map.f90 Uses Module simple_stat
# Full list of modules in ../simple_dens_map.f90: simple_math simple_stat 
# Uses simple_math which is in ../simple_math.f90
# ../simple_math.f90 already in list
# Uses simple_stat which is in ../simple_stat.f90
# ../simple_stat.f90 already in list
# Uses simple_ffts which is in ../simple_ffts.f90
# ../simple_ffts.f90 already in list
# Uses simple_params which is in ../simple_params.f90
# ../simple_params.f90 already in list
# Uses simple_math which is in ../simple_math.f90
# ../simple_math.f90 already in list
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_def_precision which is in ../simple_def_precision.f90
# ../simple_def_precision.f90 already in list
# Uses simple_math which is in ../simple_math.f90
# ../simple_math.f90 already in list
# Uses simple_build which is in ../simple_build.f90
# ../simple_build.f90 already in list
# Uses simple_params which is in ../simple_params.f90
# ../simple_params.f90 already in list
# Uses simple_rnd which is in ../simple_rnd.f90
# ../simple_rnd.f90 already in list
# Uses simple_stkspi which is in ../simple_stkspi.f90
# process_fsource called with arg ../simple_stkspi.f90 
# ../simple_stkspi.f90 Uses Module simple_jiffys
# ../simple_stkspi.f90 Uses Module simple_params
# ../simple_stkspi.f90 Uses Module simple_imgspi
# Full list of modules in ../simple_stkspi.f90: simple_jiffys simple_params simple_imgspi 
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_params which is in ../simple_params.f90
# ../simple_params.f90 already in list
# Uses simple_imgspi which is in ../simple_imgspi.f90
# ../simple_imgspi.f90 already in list
# Uses simple_imgspi which is in ../simple_imgspi.f90
# ../simple_imgspi.f90 already in list
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_ran_tabu which is in ../simple_ran_tabu.f90
# process_fsource called with arg ../simple_ran_tabu.f90 
# ../simple_ran_tabu.f90 Uses Module simple_rnd
# ../simple_ran_tabu.f90 Uses Module simple_jiffys
# Full list of modules in ../simple_ran_tabu.f90: simple_rnd simple_jiffys 
# Uses simple_rnd which is in ../simple_rnd.f90
# ../simple_rnd.f90 already in list
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_fplane which is in ../simple_fplane.f90
# ../simple_fplane.f90 already in list
# Uses simple_fstk which is in ../simple_fstk.f90
# process_fsource called with arg ../simple_fstk.f90 
# ../simple_fstk.f90 Uses Module simple_params
# ../simple_fstk.f90 Uses Module simple_fftw3
# ../simple_fstk.f90 Uses Module simple_stkspi
# ../simple_fstk.f90 Uses Module simple_imgspi
# ../simple_fstk.f90 Uses Module simple_math
# ../simple_fstk.f90 Uses Module simple_stat
# ../simple_fstk.f90 Uses Module simple_build
# ../simple_fstk.f90 Uses Module simple_jiffys
# ../simple_fstk.f90 Uses Module simple_fplane
# Full list of modules in ../simple_fstk.f90: simple_params simple_fftw3 simple_stkspi simple_imgspi simple_math simple_stat simple_build simple_jiffys simple_fplane 
# Uses simple_params which is in ../simple_params.f90
# ../simple_params.f90 already in list
# Uses simple_fftw3 which is in ../simple_fftw3.f90
# ../simple_fftw3.f90 already in list
# Uses simple_stkspi which is in ../simple_stkspi.f90
# ../simple_stkspi.f90 already in list
# Uses simple_imgspi which is in ../simple_imgspi.f90
# ../simple_imgspi.f90 already in list
# Uses simple_math which is in ../simple_math.f90
# ../simple_math.f90 already in list
# Uses simple_stat which is in ../simple_stat.f90
# ../simple_stat.f90 already in list
# Uses simple_build which is in ../simple_build.f90
# ../simple_build.f90 already in list
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_fplane which is in ../simple_fplane.f90
# ../simple_fplane.f90 already in list
# Uses simple_spidoc which is in ../simple_spidoc.f90
# ../simple_spidoc.f90 already in list
# Uses simple_params which is in ../simple_params.f90
# ../simple_params.f90 already in list
# Uses simple_sll_list which is in ../simple_sll_list.f90
# ../simple_sll_list.f90 already in list
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_build which is in ../simple_build.f90
# ../simple_build.f90 already in list
# Uses simple_ppca which is in ../simple_ppca.f90
# process_fsource called with arg ../simple_ppca.f90 
# ../simple_ppca.f90 Uses Module simple_params
# ../simple_ppca.f90 Uses Module simple_jiffys
# ../simple_ppca.f90 Uses Module simple_rnd
# ../simple_ppca.f90 Uses Module simple_math
# ../simple_ppca.f90 Uses Module simple_fplane
# ../simple_ppca.f90 Uses Module simple_def_precision
# Full list of modules in ../simple_ppca.f90: simple_params simple_jiffys simple_rnd simple_math simple_fplane simple_def_precision 
# Uses simple_params which is in ../simple_params.f90
# ../simple_params.f90 already in list
# Uses simple_jiffys which is in ../simple_jiffys.f90
# ../simple_jiffys.f90 already in list
# Uses simple_rnd which is in ../simple_rnd.f90
# ../simple_rnd.f90 already in list
# Uses simple_math which is in ../simple_math.f90
# ../simple_math.f90 already in list
# Uses simple_fplane which is in ../simple_fplane.f90
# ../simple_fplane.f90 already in list
# Uses simple_def_precision which is in ../simple_def_precision.f90
# ../simple_def_precision.f90 already in list
# Uses simple_pair_wtab which is in ../simple_pair_wtab.f90
# ../simple_pair_wtab.f90 already in list
# Uses simple_math which is in ../simple_math.f90
# ../simple_math.f90 already in list
# Uses simple_cmdline which is in ../simple_cmdline.f90
# ../simple_cmdline.f90 already in list

# ------------------Macro-Defs---------------------
F90=ifort 

# -------------------End-macro-Defs---------------------------

# Here is the link step 
classify:simple_i_scalar.o simple_r_scalar.o simple_def_precision.o simple_d_scalar.o simple_jiffys.o simple_i_array.o simple_r_array.o simple_d_array.o simple_list_object.o simple_sll_list.o simple_syscalls.o simple_rnd.o simple_math.o simple_heapsort.o simple_spidoc.o simple_eulers.o simple_cmdline.o simple_params.o simple_comlin.o simple_aligndata.o simple_pair_wtab.o simple_stat.o simple_volspi.o simple_fftw3.o simple_ffts.o gnufor2.o simple_dens_map.o simple_imgspi.o simple_fplane.o simple_build.o simple_fplanes_corr.o simple_stkspi.o simple_ran_tabu.o simple_pmatch.o simple_fstk.o simple_ppca.o classify.o 
	 $(F90) -o classify simple_i_scalar.o simple_r_scalar.o simple_def_precision.o simple_d_scalar.o simple_jiffys.o simple_i_array.o simple_r_array.o simple_d_array.o simple_list_object.o simple_sll_list.o simple_syscalls.o simple_rnd.o simple_math.o simple_heapsort.o simple_spidoc.o simple_eulers.o simple_cmdline.o simple_params.o simple_comlin.o simple_aligndata.o simple_pair_wtab.o simple_stat.o simple_volspi.o simple_fftw3.o simple_ffts.o gnufor2.o simple_dens_map.o simple_imgspi.o simple_fplane.o simple_build.o simple_fplanes_corr.o simple_stkspi.o simple_ran_tabu.o simple_pmatch.o simple_fstk.o simple_ppca.o classify.o   -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

# Here are the compile steps
 
simple_i_scalar.o:../simple_i_scalar.f90  
	 $(F90) -c ../simple_i_scalar.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_r_scalar.o:../simple_r_scalar.f90  
	 $(F90) -c ../simple_r_scalar.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_def_precision.o:../simple_def_precision.f90  
	 $(F90) -c ../simple_def_precision.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_d_scalar.o:../simple_d_scalar.f90 simple_def_precision.o 
	 $(F90) -c ../simple_d_scalar.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_jiffys.o:../simple_jiffys.f90  
	 $(F90) -c ../simple_jiffys.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_i_array.o:../simple_i_array.f90 simple_jiffys.o 
	 $(F90) -c ../simple_i_array.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_r_array.o:../simple_r_array.f90 simple_jiffys.o 
	 $(F90) -c ../simple_r_array.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_d_array.o:../simple_d_array.f90 simple_def_precision.o simple_jiffys.o 
	 $(F90) -c ../simple_d_array.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_list_object.o:../simple_list_object.f90 simple_i_scalar.o simple_r_scalar.o simple_d_scalar.o simple_i_array.o simple_r_array.o simple_d_array.o 
	 $(F90) -c ../simple_list_object.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_sll_list.o:../simple_sll_list.f90 simple_list_object.o simple_def_precision.o 
	 $(F90) -c ../simple_sll_list.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_syscalls.o:../simple_syscalls.f90  
	 $(F90) -c ../simple_syscalls.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_rnd.o:../simple_rnd.f90  
	 $(F90) -c ../simple_rnd.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_math.o:../simple_math.f90 simple_def_precision.o simple_syscalls.o simple_jiffys.o simple_rnd.o 
	 $(F90) -c ../simple_math.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_heapsort.o:../simple_heapsort.f90 simple_sll_list.o simple_math.o simple_def_precision.o 
	 $(F90) -c ../simple_heapsort.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_spidoc.o:../simple_spidoc.f90 simple_sll_list.o simple_jiffys.o 
	 $(F90) -c ../simple_spidoc.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_eulers.o:../simple_eulers.f90 simple_heapsort.o simple_math.o simple_def_precision.o simple_spidoc.o simple_jiffys.o 
	 $(F90) -c ../simple_eulers.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_cmdline.o:../simple_cmdline.f90  
	 $(F90) -c ../simple_cmdline.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_params.o:../simple_params.f90 simple_jiffys.o simple_cmdline.o simple_math.o 
	 $(F90) -c ../simple_params.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_comlin.o:../simple_comlin.f90 simple_eulers.o simple_math.o simple_jiffys.o simple_params.o 
	 $(F90) -c ../simple_comlin.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_aligndata.o:../simple_aligndata.f90 simple_heapsort.o simple_jiffys.o 
	 $(F90) -c ../simple_aligndata.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_pair_wtab.o:../simple_pair_wtab.f90 simple_jiffys.o 
	 $(F90) -c ../simple_pair_wtab.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_stat.o:../simple_stat.f90 simple_def_precision.o simple_pair_wtab.o simple_sll_list.o simple_jiffys.o simple_math.o simple_rnd.o simple_params.o 
	 $(F90) -c ../simple_stat.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_volspi.o:../simple_volspi.f90 simple_math.o simple_jiffys.o simple_params.o simple_stat.o 
	 $(F90) -c ../simple_volspi.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_fftw3.o:../simple_fftw3.f90  
	 $(F90) -c ../simple_fftw3.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_ffts.o:../simple_ffts.f90 simple_fftw3.o simple_jiffys.o 
	 $(F90) -c ../simple_ffts.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

gnufor2.o:../gnufor2.f90  
	 $(F90) -c ../gnufor2.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_dens_map.o:../simple_dens_map.f90 simple_math.o simple_stat.o 
	 $(F90) -c ../simple_dens_map.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_imgspi.o:../simple_imgspi.f90 simple_math.o gnufor2.o simple_jiffys.o simple_stat.o simple_params.o simple_dens_map.o 
	 $(F90) -c ../simple_imgspi.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_fplane.o:../simple_fplane.f90 simple_math.o simple_jiffys.o simple_params.o simple_stat.o simple_imgspi.o simple_ffts.o 
	 $(F90) -c ../simple_fplane.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_build.o:../simple_build.f90 simple_params.o simple_eulers.o simple_comlin.o simple_heapsort.o simple_aligndata.o simple_volspi.o simple_jiffys.o simple_math.o simple_rnd.o simple_ffts.o simple_fplane.o 
	 $(F90) -c ../simple_build.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_fplanes_corr.o:../simple_fplanes_corr.f90 simple_eulers.o simple_build.o simple_params.o simple_math.o simple_jiffys.o simple_def_precision.o 
	 $(F90) -c ../simple_fplanes_corr.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_stkspi.o:../simple_stkspi.f90 simple_jiffys.o simple_params.o simple_imgspi.o 
	 $(F90) -c ../simple_stkspi.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_ran_tabu.o:../simple_ran_tabu.f90 simple_rnd.o simple_jiffys.o 
	 $(F90) -c ../simple_ran_tabu.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_pmatch.o:../simple_pmatch.f90 simple_fplanes_corr.o simple_math.o simple_build.o simple_params.o simple_rnd.o simple_stkspi.o simple_imgspi.o simple_jiffys.o simple_ran_tabu.o simple_fplane.o 
	 $(F90) -c ../simple_pmatch.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_fstk.o:../simple_fstk.f90 simple_params.o simple_fftw3.o simple_stkspi.o simple_imgspi.o simple_math.o simple_stat.o simple_build.o simple_jiffys.o simple_fplane.o 
	 $(F90) -c ../simple_fstk.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

simple_ppca.o:../simple_ppca.f90 simple_params.o simple_jiffys.o simple_rnd.o simple_math.o simple_fplane.o simple_def_precision.o 
	 $(F90) -c ../simple_ppca.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static

classify.o:classify.f90 simple_pmatch.o simple_fstk.o simple_spidoc.o simple_params.o simple_sll_list.o simple_jiffys.o simple_build.o simple_ppca.o simple_pair_wtab.o simple_math.o simple_cmdline.o 
	 $(F90) -c classify.f90 -implicitnone -openmp -m64 -L../fftw/fftw3-osx-64/lib/ -lfftw3f -lfftw3f_threads -i-static
# This entry allows you to type " make clean " to get rid of
# all object and module files 
clean:
	rm -f -r f_{files,modd}* *~ *.g90 *.o *.mod *.M *.d V*.inc *.vo \
	V*.f *.dbg album F.err
  
