/**********************************************************************

	--- Qt Architect generated file ---

	File: D2InspectorData.h
	Last generated: Thu Apr 25 00:43:20 2002

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef D2InspectorData_included
#define D2InspectorData_included

#include <qdialog.h>
#include "qwidgetstack.h"
#include <qtabbar.h>

class D2InspectorData : public QDialog
{
    Q_OBJECT

public:

    D2InspectorData(QWidget *parent = NULL, const char *name = NULL);

    virtual ~D2InspectorData();

    protected slots:

    virtual void tabSel(int) =0;

    protected:

    QTabBar *tabs;
    QWidgetStack *stack;
};

#endif // D2InspectorData_included
