/**********************************************************************

	--- Qt Architect generated file ---

	File: ImageMxConData.h
	Last generated: Thu Apr 25 00:55:03 2002

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef ImageMxConData_included
#define ImageMxConData_included

#include <qdialog.h>
#include <qlabel.h>
#include "MiniImage.h"
#include <qpushbutton.h>
#include <qcheckbox.h>
#include "ValSlider.h"
#include <qlineedit.h>
#include "ImHist.h"

class ImageMxConData : public QDialog
{
    Q_OBJECT

public:

    ImageMxConData(QWidget *parent = NULL, const char *name = NULL);

    virtual ~ImageMxConData();

    protected:

    QCheckBox *invert;
    QCheckBox *label;
    QPushButton *bsaveFile;
    QCheckBox *label2;
    QPushButton *bsave;
    QPushButton *modeApp;
    QPushButton *modeDel;
    QPushButton *modeMove;
    QLineEdit *scale;
    QPushButton *bprint;
    ImHist *hist;
    QCheckBox *showhist;
    QPushButton *modeSplit;
    MiniImage *mini;
    QLabel *loc;
    ValSlider *brt;
    ValSlider *cont;
    QPushButton *modeProbe;
    QCheckBox *showfft;
};

#endif // ImageMxConData_included
