/**********************************************************************

	--- Qt Architect generated file ---

	File: InspPlotGenData.h
	Last generated: Thu Apr 25 00:43:24 2002

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef InspPlotGenData_included
#define InspPlotGenData_included

#include <qwidget.h>

class InspPlotGenData : public QWidget
{
    Q_OBJECT

public:

    InspPlotGenData(QWidget *parent = NULL, const char *name = NULL);

    virtual ~InspPlotGenData();
};

#endif // InspPlotGenData_included
