/**********************************************************************

	--- Qt Architect generated file ---

	File: InspAreaData.h
	Last generated: Thu Apr 25 00:43:38 2002

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef InspAreaData_included
#define InspAreaData_included

#include <qwidget.h>
#include <qpushbutton.h>
#include <qcheckbox.h>
#include <qcombobox.h>
#include <qlineedit.h>

class InspAreaData : public QWidget
{
    Q_OBJECT

public:

    InspAreaData(QWidget *parent = NULL, const char *name = NULL);

    virtual ~InspAreaData();

    protected slots:

    virtual void newCBTitle(bool) =0;
    virtual void newAxLW(int) =0;
    virtual void newCBLBox(bool) =0;
    virtual void newXTitle() =0;
    virtual void newShowY0(bool) =0;
    virtual void newLFont() =0;
    virtual void newCBLR(bool) =0;
    virtual void newYTitle() =0;
    virtual void newFrameLw(int) =0;
    virtual void newAnimZ(bool) =0;
    virtual void newCBXAX(bool) =0;
    virtual void newCBYAX(bool) =0;
    virtual void newCBLegend(bool) =0;
    virtual void newTFont() =0;
    virtual void savepng() =0;
    virtual void print() =0;
    virtual void newFrameColor() =0;
    virtual void newAxColor() =0;
    virtual void newCBYTitle(bool) =0;
    virtual void newCBFrame(bool) =0;
    virtual void newCBXTitle(bool) =0;
    virtual void newTitle() =0;

    protected:

    QLineEdit *title;
    QCheckBox *cbtitle;
    QCheckBox *cbframe;
    QCheckBox *cblr;
    QCheckBox *cbshowy0;
    QCheckBox *cbanimz;
    QLineEdit *ytitle;
    QLineEdit *xtitle;
    QCheckBox *cbytitle;
    QCheckBox *cbxtitle;
    QCheckBox *cblegend;
    QCheckBox *cblbox;
    QComboBox *framelw;
    QPushButton *framecolor;
    QCheckBox *cbxax;
    QCheckBox *cbyax;
    QComboBox *axlw;
    QPushButton *axcolor;
};

#endif // InspAreaData_included
