/**********************************************************************

	--- Qt Architect generated file ---

	File: InspAxisData.h
	Last generated: Thu Apr 25 00:43:27 2002

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef InspAxisData_included
#define InspAxisData_included

#include <qwidget.h>
#include <qcheckbox.h>
#include <qpushbutton.h>
#include <qcombobox.h>
#include <qlineedit.h>

class InspAxisData : public QWidget
{
    Q_OBJECT

public:

    InspAxisData(QWidget *parent = NULL, const char *name = NULL);

    virtual ~InspAxisData();

    protected slots:

    virtual void newCBTitle(bool) =0;
    virtual void newMinGrid(bool) =0;
    virtual void newMaj() =0;
    virtual void newMax() =0;
    virtual void newMin() =0;
    virtual void newCBLog(bool) =0;
    virtual void newTFont() =0;
    virtual void newAuto(bool) =0;
    virtual void newAFont() =0;
    virtual void newCBAxis(bool) =0;
    virtual void newAxisColor() =0;
    virtual void newMinor(int) =0;
    virtual void newMajGrid(bool) =0;
    virtual void newMajTick(bool) =0;
    virtual void newTitle() =0;

    protected:

    QLineEdit *title;
    QPushButton *tfont;
    QLineEdit *min;
    QLineEdit *max;
    QPushButton *autos;
    QPushButton *majtick;
    QPushButton *afont;
    QPushButton *majgrid;
    QPushButton *mingrid;
    QLineEdit *maj;
    QComboBox *minor;
    QCheckBox *cbtitle;
    QPushButton *axiscolor;
    QCheckBox *cbaxis;
    QCheckBox *cblog;
};

#endif // InspAxisData_included
