/**********************************************************************

	--- Qt Architect generated file ---

	File: InspPlotDsetData.h
	Last generated: Thu Apr 25 00:43:33 2002

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef InspPlotDsetData_included
#define InspPlotDsetData_included

#include <qwidget.h>

class InspPlotDsetData : public QWidget
{
    Q_OBJECT

public:

    InspPlotDsetData(QWidget *parent = NULL, const char *name = NULL);

    virtual ~InspPlotDsetData();
};

#endif // InspPlotDsetData_included
