/**********************************************************************

	--- Qt Architect generated file ---

	File: LSPlotInspData.h
	Last generated: Thu Apr 25 00:43:43 2002

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef LSPlotInspData_included
#define LSPlotInspData_included

#include <qwidget.h>
#include <qpushbutton.h>
#include <qcombobox.h>
#include <qlineedit.h>

class LSPlotInspData : public QWidget
{
    Q_OBJECT

public:

    LSPlotInspData(QWidget *parent = NULL, const char *name = NULL);

    virtual ~LSPlotInspData();

    protected slots:

    virtual void setLS(int) =0;
    virtual void setSym(int) =0;
    virtual void lineTog(bool) =0;
    virtual void symTog(bool) =0;
    virtual void setVec(int) =0;
    virtual void setCol() =0;
    virtual void setSSz(int) =0;
    virtual void setCMode(int) =0;
    virtual void setLW(int) =0;

    protected:

    QPushButton *symtog;
    QComboBox *symsel;
    QPushButton *linetog;
    QComboBox *lwsel;
    QComboBox *linesel;
    QLineEdit *xcol;
    QLineEdit *ycol;
    QLineEdit *vxcol;
    QLineEdit *vycol;
    QComboBox *colsel;
    QLineEdit *c1col;
    QLineEdit *c2col;
    QLineEdit *c3col;
    QComboBox *vecsel;
    QComboBox *sssel;
};

#endif // LSPlotInspData_included
